### ISSUE TITLE
Gutter highlight too subtle

### ISSUE THREAD

**Issue by peterjhart** [elliotwaite/jetbrains-cyberpunk-theme#2]
I really, really like this theme. This morning I accepted an update, and the portions of the gutter that show which lines contain changes is too subtle. I rely on these indicators constantly.

In Webstorm on my Mac, the gutter base color is #343434. The color in the gutter (next to the line numbers) for lines with code changes (according to git) is #3B3B3B.

Is the color changed caused by this theme? If so, can it be referted, or made to stand out more, like D566C3 (fucsia) or #00F0FF (cyan)?

Cyberpunk Theme 1.0.6
Webstorm 2021.1.2
macOS 10.15.7

**Comment by elliotwaite** [comment]
The recent update should not have affected those colors, however, I did rename the color scheme (`Preferences > Editor > Color Scheme`) from "Cyberpunk" to "Cyberpunk Theme" so that it would be consistent with the name of the theme (`Preferences > Appearance & Behavior > Appearance > Theme`) which is "Cyberpunk Theme". I'm not sure, but this change may have caused any customizations you may have made to the "Cyberpunk" theme to be reverted back to their default values in the newly named "Cyberpunk Theme" color scheme. If this is true, I apologize, I did not consider that possible side effect until now. Also, I won't be changing the color scheme's name anymore in the future, so this should be the last time this could be an issue.

You should be able to customize the VCS gutter colors by going to:
* Preferences > Editor > Color Scheme > VCS
And then under the "Editor Gutter" section, there should be "Added lines", "Deleted lines", "Modified lines", and some others you can change. You just click them and then change the "Background" color in the right panel.

Let me know if this works for you.

You can also see in that same section if there is an option to change the "Scheme" dropdown menu from "Cyberpunk Theme" to "Cyberpunk" (which may be leftover from the previous version). If so, you can see if the VCS gutter colors in that color scheme were different than in this latest version.

In the past, I tried setting the VCS gutter colors to be brighter, but I found them distracting, so I made them subtler, which is just my personal preference. For now, I think I'll keep the colors that come with the theme as the subtler ones, but I may experiment with updating them in the future. Thanks for the suggestion.

**Comment by peterjhart** [comment]
Thank you for your quick response. I didn't realize how complicated WebStorm's appearance configuration is; I didn't know about the settings in Preferences > Editor > Color Scheme.

So I have your theme installed, but I also have a Cyberpunk UI plugin (no offense): 
https://plugins.jetbrains.com/plugin/15775-cyberpunkui-color-scheme

It looks I need to have both your theme and the plugin enabled, and something got reset. Thanks for helping me figure it out.

**Comment by elliotwaite** [comment]
Ah, got it. The Cyberpunk combo, hah, nice. Glad to hear you were able to figure it out.

I'm going to close this issue, but if you run into any other issues, feel free to reopen this issue or create a new issue.
